version: "3.7"
services:
  database:
    container_name: database.adsolo-k8s.com
    image: "mongo:4.2.3"
    ports:
      - "27017:27017"
    env_file: .env
    volumes:
      - ./backend/database/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh

  backend:
    container_name: api.adsolo-k8s.com
    ports:
      - 2000:3000
    build:
      context: backend/api
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database

  frontend:
    container_name: adsolo-k8s.com
    ports:
      - 3000:3000
    build:
      context: frontend/home
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - backend

  app:
    container_name: app.adsolo-k8s.com
    ports:
      - 3002:80
    build:
      context: frontend/app
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_SERVICE_URL=http://backend:2000
        - REACT_APP_BACKEND_DOMAIN_URL=http://localhost:2000
    env_file: .env
    stdin_open: true
    depends_on:
      - backend

  admin:
    container_name: admin.adsolo-k8s.com
    ports:
      - 3001:3000
    build:
      context: frontend/admin
      dockerfile: Dockerfile
    env_file: .env


  https:
    image: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - URL_FRONTEND_ADMIN=https://adsolo-k8s-dev.com
      - URL_FRONTEND_HOME=https://admin.adsolo-k8s-dev.com
      - URL_FRONTEND_APP=https://api.larler-dev.com
      - URL_BACKEND=https://app.adsolo-k8s-dev.com
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  database-seed:
    image: "mongo:4.2.3"
    container_name: seed.adsolo-k8s.com
    command: "/backend/database/seed.sh"
    env_file: .env
    volumes:
      - ./backend/database/restore:/db
      - ./backend/database/seed.sh:/backend/database/seed.sh
    depends_on:
      - database