version: "3.7"
services:
  database:
    container_name: database.adsolo-k8s-dev.com
    image: "mongo:4.2.3"
    ports:
      - "27017:27017"
    volumes:
      - ./deploy/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    env_file: .env

  backend:
    container_name: api.adsolo-k8s-dev.com
    ports:
      - 2000:3000
    build:
      context: backend/api
      dockerfile: dev.Dockerfile
    env_file: .env
    volumes:
      - ./backend/api:/app
      - ./backend/api/public/uploads:/app/public/uploads
      - ./backend/api/public/images:/app/public/images
      - /app/node_modules
    depends_on:
      - database

  frontend:
    container_name: adsolo-k8s-dev.com
    ports:
      - 3000:3000
    build:
      context: frontend/home
      dockerfile: dev.Dockerfile
    env_file: .env
    volumes:
      - ./frontend/home:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  app:
    container_name: app.adsolo-k8s-dev.com
    ports:
      - 3002:3000
    build:
      context: frontend/app
      dockerfile: dev.Dockerfile
    env_file: .env
    stdin_open: true
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    depends_on:
      - backend

  admin:
    container_name: admin.adsolo-k8s-dev.com
    ports:
      - 3001:3000
    build:
      context: frontend/admin
      dockerfile: dev.Dockerfile
    env_file: .env
    volumes:
      - ./frontend/admin:/app
      - /app/node_modules
      - /app/.next

  https:
    image: caddy
    ports:
      - 80:80
      - 443:443
    env_file: .env
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  # database-seed:
  #   image: "mongo:4.2.3"
  #   container_name: seed.adsolo-k8s-dev.com
  #   command: "/deploy/init-mongo.sh"
  #   env_file: .env
  #   volumes:
  #     - ./db:/db
  #     - ./deploy/init-mongo.sh:/deploy/init-mongo.sh
  #   depends_on:
  #     - database
